[package]
name = "che-tauri"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
che-orm = { path = "../che-orm/crates/che-orm" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", default-features = false, features = ["json", "query", "rustls"] }
tauri = "2"
thiserror = "2"
toml = "0.8"
